### ISSUE TITLE
Ignoring syncmap.yml

### ISSUE THREAD

**Issue by sokolewicz** [github/github-team-sync#114]
I've set up my .env file to LDAP config and the problem I'm having is that users are being added to all teams in organization, not the one I described in syncmap.yml.
syncmap.yml:
```
---
mapping:
  - github: test
    directory: github_users
```

test is a team I made in my organization, github_users is a LDAP group I want to sync there.
